name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y git make clang perl dpkg wget xz-utils pkg-config \
          libplist-dev libplist++-dev libplist-utils libssl-dev libcrypto++-dev libz-dev
    
    - name: Build ldid from source
      run: |
        git clone https://github.com/ProcursusTeam/ldid.git
        cd ldid
        make
        sudo make install
        cd ..
    
    - name: Clone Theos
      run: |
        sudo git clone --recursive https://github.com/theos/theos.git /opt/theos
        sudo chmod -R 755 /opt/theos
    
    - name: Download SDK from xybp888
      run: |
        sudo mkdir -p /opt/theos/sdks
        cd /opt/theos/sdks
        sudo wget https://github.com/xybp888/iOS-SDKs/releases/download/iOS-14.5-SDK/iPhoneOS14.5.sdk.tar.xz
        sudo tar -xf iPhoneOS14.5.sdk.tar.xz
        ls -la
    
    - name: Build Tweak
      run: |
        export THEOS=/opt/theos
        make package
    
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: HDangDynamic
        path: packages/*.deb
